### ISSUE TITLE
Incompatible mod set to 'spruceui'

### ISSUE THREAD

**Issue by doonv** [LambdAurora/LambDynamicLights#123]
**Describe the bug**
The game doesnt open due to Incompatible mod set

**To Reproduce**
1. Launch the game i guess

**Expected behavior**
The game runs

**Screenshots**
![image](https://user-images.githubusercontent.com/58695417/195931710-f8131aa0-8d45-468d-9299-9f813b8b7f09.png)

**Log**
<details>
<summary>Click to show log</summary>
<br>
<pre>
PolyMC version: 1.4.2

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.251.38, 13.225.251.52, 13.225.251.65, 13.225.251.47]

session.minecraft.net resolves to:
    [34.199.236.154, 100.24.172.95, 35.153.153.200]

textures.minecraft.net resolves to:
    [65.9.112.120, 65.9.112.117, 65.9.112.111, 65.9.112.45]

api.mojang.com resolves to:
    [13.226.2.94, 13.226.2.92, 13.226.2.127, 13.226.2.104]

Minecraft folder is:
C:/Users/dkap2/AppData/Roaming/PolyMC/instances/1.19.2 for sane people/.minecraft

Java path is:
C:/Program Files/Java/jdk-17.0.4.1/bin/javaw.exe

Checking Java version...
Java is version 17.0.4.1, using 64 (amd64) architecture, from Oracle Corporation.

Main Class:
  org.quiltmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/dkap2/AppData/Roaming/PolyMC/instances/1.19.2 for sane people/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.1/lwjgl-glfw-natives-windows-x86-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.1/lwjgl-glfw-natives-windows-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.1/lwjgl-jemalloc-natives-windows-x86-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.1/lwjgl-jemalloc-natives-windows-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.1/lwjgl-natives-windows-x86-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-natives-windows/3.3.1/lwjgl-natives-windows-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.1/lwjgl-openal-natives-windows-x86-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.1/lwjgl-openal-natives-windows-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.1/lwjgl-opengl-natives-windows-x86-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.1/lwjgl-opengl-natives-windows-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.1/lwjgl-stb-natives-windows-x86-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.1/lwjgl-stb-natives-windows-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.1/lwjgl-tinyfd-natives-windows-x86-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.1/lwjgl-tinyfd-natives-windows-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.1/log4j-slf4j18-impl-2.17.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/mojang/text2speech-natives-windows/1.13.9/text2speech-natives-windows-1.13.9.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/net/fabricmc/intermediary/1.19.2/intermediary-1.19.2.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/quiltmc/quilt-json5/1.0.1/quilt-json5-1.0.1.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/quiltmc/quilt-config/1.0.0-beta.5/quilt-config-1.0.0-beta.5.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/org/quiltmc/quilt-loader/0.17.4/quilt-loader-0.17.4.jar
  C:/Users/dkap2/AppData/Roaming/PolyMC/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:

Mods:
  [✘] indium-1.0.9+mc1.19.2.jar (disabled)
  [✔] lambdynamiclights-2.1.2+1.19
  [✘] lithium-fabric-mc1.19.2-0.9.1.jar (disabled)
  [✔] modmenu-4.0.6
  [✘] sodium-extra-0.4.11+mc1.19.2-build.68.jar (disabled)
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✘] starlight-1.1.1+fabric.ae22326.jar (disabled)

Params:
  --username  --version 1.19.2 --gameDir C:/Users/dkap2/AppData/Roaming/PolyMC/instances/1.19.2 for sane people/.minecraft --assetsDir C:/Users/dkap2/AppData/Roaming/PolyMC/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 1628

[22:58:16] [main/INFO]: Loading Minecraft 1.19.2 with Quilt Loader 0.17.4
[22:58:17] [main/ERROR]: Incompatible mod set!
org.quiltmc.loader.impl.FormattedException: org.quiltmc.loader.impl.discovery.ModSolvingException: Found 2 errors while resolving mods!
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:214) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:141) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) [quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: org.quiltmc.loader.impl.discovery.ModSolvingException: Found 2 errors while resolving mods!
	at org.quiltmc.loader.impl.solver.ModSolver.findCompatibleSet(ModSolver.java:266) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:432) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:223) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:212) ~[quilt-loader-0.17.4.jar:?]
	... 12 more
	Suppressed: org.quiltmc.loader.impl.discovery.ModSolvingException: Unhandled error involving mod 'LambDynamicLights' (lambdynlights) v2.1.2+1.19:
Dependency for mod 'lambdynlights' on fabric versions [>=0.55.3+1.19] (0 valid options, 0 invalid options)
		at org.quiltmc.loader.impl.solver.ModSolver.fallbackErrorDescription(ModSolver.java:615) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.solver.ModSolver.findCompatibleSet(ModSolver.java:244) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:432) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:223) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:212) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:141) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) [quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.4.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
		at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
		at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
		at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
		at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
	Suppressed: org.quiltmc.loader.impl.discovery.ModSolvingException: Unhandled error involving mod 'LambDynamicLights' (lambdynlights) v2.1.2+1.19:
Dependency for mod 'spruceui' on fabric-rendering-v1 versions [*] (0 valid options, 0 invalid options)
Dependency for mod 'lambdynlights' on spruceui versions [>=4.0.0] (1 valid options, 0 invalid options)
	+ mod 'spruceui' version 4.0.0+1.19 loaded from mods\lambdynamiclights-2.1.2+1.19.jar!/META-INF/jars/spruceui-4.0.0+1.19.jar
		at org.quiltmc.loader.impl.solver.ModSolver.fallbackErrorDescription(ModSolver.java:615) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.solver.ModSolver.findCompatibleSet(ModSolver.java:244) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:432) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:223) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:212) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:141) ~[quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) [quilt-loader-0.17.4.jar:?]
		at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.4.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
		at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
		at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
		at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
		at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
</pre>
</details>

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.19.2
 - Quilt Loader version 0.17.4
 - Mods: sodium-fabric-mc1.19.2-0.4.4+build.18, lambdynamiclights-2.1.2+1.19, modmenu-4.0.6
 - Version 2.1.2
 - Branch mc1.19

**Comment by LambdAurora** [comment]
Install Fabric API.
