### ISSUE TITLE
Mod Menu Settings Game Crash 1.20.2

### ISSUE THREAD

**Issue by nco2k** [LambdAurora/LambDynamicLights#186]
opening up mod menu and clicking on the settings button of lambdynamiclights makes the game crash with following error:
- The game crashed whilst rendering screen
- Error: java.lang.NoSuchFieldError: field_22757
- Exit Code: -1073740791

im using the latest files:
- fabric-api-0.89.2+1.20.2.jar
- lambdynamiclights-2.3.2+1.20.1.jar
- modmenu-8.0.0.jar

**Comment by verified-gamer** [comment]
i have the same issue, same mods, same chrash reason.
log file: [https://paste.ee/p/rVkFV](https://paste.ee/p/rVkFV)

**Comment by SeamusFinlayson** [comment]
Same problem, using this as part of the additive mod pack.

**Comment by SeamusFinlayson** [comment]
For any other modding newbies like me, the setting are still accessible in the lambdynlights.toml config file.

**Comment by machiecodes** [comment]
Can confirm

**Comment by Redband99** [comment]
I can also confirm I am having the same issue

**Comment by SerosKanjus** [comment]
Likewise

**Comment by LessThanBenji** [comment]
experiencing the same issue, same setup as op :)

**Comment by symoner66** [comment]
still no answer for this bug?

**Comment by Object417** [comment]
Same issue.

```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:?]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.utils.TransformingIterator.next(TransformingIterator.java:34) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:57) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:47) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:92) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:47) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:92) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:47) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:92) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:47) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:92) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:47) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TomlWriter.write(TomlWriter.java:30) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.file.WriteAsyncFileConfig.save(WriteAsyncFileConfig.java:114) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.file.WriteAsyncFileConfig.access$300(WriteAsyncFileConfig.java:23) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.file.WriteAsyncFileConfig$WriteCompletedHandler.completed(WriteAsyncFileConfig.java:147) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.file.WriteAsyncFileConfig$WriteCompletedHandler.completed(WriteAsyncFileConfig.java:142) ~[lambdynamiclights-2.3.2+1.20.1.jar:?]
	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source) ~[?:?]
	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source) ~[?:?]
	at sun.nio.ch.WindowsAsynchronousFileChannelImpl$WriteTask.completed(Unknown Source) ~[?:?]
	at sun.nio.ch.Iocp$EventHandlerTask.run(Unknown Source) ~[?:?]
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

[Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:955) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.14.23.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.23.jar:?]
Caused by: java.lang.NoSuchFieldError: field_22757
	at dev.lambdaurora.spruceui.widget.AbstractSpruceButtonWidget.renderBackground(AbstractSpruceButtonWidget.java:157) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:263) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.container.SpruceOptionListWidget$OptionEntry.lambda$renderWidget$1(SpruceOptionListWidget.java:222) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at dev.lambdaurora.spruceui.widget.container.SpruceOptionListWidget$OptionEntry.renderWidget(SpruceOptionListWidget.java:222) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.container.SpruceEntryListWidget.lambda$renderWidget$0(SpruceEntryListWidget.java:340) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at dev.lambdaurora.spruceui.widget.container.SpruceEntryListWidget.renderWidget(SpruceEntryListWidget.java:340) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.container.SpruceContainerWidget.lambda$renderWidget$0(SpruceContainerWidget.java:82) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at dev.lambdaurora.spruceui.widget.container.SpruceContainerWidget.renderWidget(SpruceContainerWidget.java:82) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.container.tabbed.SpruceTabbedWidget.renderWidget(SpruceTabbedWidget.java:161) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.screen.SpruceScreen.renderWidgets(SpruceScreen.java:128) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.screen.SpruceScreen.method_25394(SpruceScreen.java:116) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
	... 6 more
```

**Comment by S1700** [comment]
So mod menu hides the mod's config file, is there any way to fix it? Or do we have to stick to editing the config file?

**Comment by LambdAurora** [comment]
> So mod menu hides the mod's config file, is there any way to fix it? Or do we have to stick to editing the config file?

Please make sure you have updated the mod and give more information about your environment if the issue persists.
