### ISSUE TITLE
LambDynamicLights error in Fabric 1.20.1 Help

### ISSUE THREAD

**Issue by ZLOYCUMSHOT** [LambdAurora/LambDynamicLights#208]
Picked up _JAVA_OPTIONS: 
[08:44:11] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.7
[08:44:11] [main/WARN]: Warnings were found!
 - Mod 'LambDynamicLights' (lambdynlights) 2.3.2+1.20.1 recommends version 0.19.1 or later of quilt_loader, which is missing!
	 - You should install version 0.19.1 or later of quilt_loader for the optimal experience.
[08:44:11] [main/INFO]: Loading 212 mods:
	- ambientsounds 5.3.8
	- appleskin 2.5.1+mc1.20
	- bclib 3.0.14
	   \-- wunderlib 1.1.5
	- bendy-lib 4.0.0
	- betterend 4.0.11
	- betterf3 7.0.2
	- betternether 9.0.10
	- blur 3.1.0
	   \-- satin 1.13.0
	- bobby 5.0.1
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- c2me 0.2.0+alpha.11.4
	   |-- c2me-base 0.2.0+alpha.11.4
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.4
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.4
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.4
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.4
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.4
	   |-- c2me-notickvd 0.2.0+alpha.11.4
	   |-- c2me-opts-allocs 0.2.0+alpha.11.4
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.4
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.4
	   |-- c2me-opts-math 0.2.0+alpha.11.4
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.4
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.4
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.4
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.4
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.4
	   |-- c2me-server-utils 0.2.0+alpha.11.4
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.4
	   |-- c2me-threading-lighting 0.2.0+alpha.11.4
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.4
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- camerautils 1.20.1-1.0.5
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- carpet 1.4.112+v230608
	- carpet-fixes 1.20-1.16.1
	- citresewn 1.1.3+1.20
	   \-- citresewn-defaults 1.1.3+1.20
	- clickthrough 1.20-fabric0.83.0-0.4.1
	   |-- crowdin-translate 1.4+1.19.3
	   \-- gbfabrictools 1.4+1.20
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- clumps 12.0.0.3
	- creativecore 2.11.15
	   \-- net_minecraftforge_eventbus 6.0.3
	- ctov 3.4.2
	- cullleaves 3.2.0
	- dashloader 5.0.0-beta.2+1.20.0
	   |-- com_github_luben_zstd-jni 1.5.2-2
	   |-- dev_notalpha_taski 2.1.0
	   \-- dev_quantumfusion_hyphen 0.4.0-rc.3
	- dawn 5.0.0
	   |-- terraform-shapes-api-v1 7.0.1
	   \-- terraform-wood-api-v1 7.0.1
	- dsurround 0.3.2
	   \-- org_openjdk_nashorn_nashorn-core 15.4
	- eatinganimationid 1.20+1.9.5
	- emotecraft 2.2.7-b.build.50
	- enhancedblockentities 0.9+1.20
	   |-- advanced_runtime_resource_pack 0.6.7
	   \-- spruceui 5.0.0+1.20
	- entity_model_features 1.2.3
	- entity_texture_features 5.2.3
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.2-mc1.20
	- fabric-api 0.91.1+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.5.23+1802ada577
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.4+1802ada577
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- ferritecore 6.0.1
	- geckolib 4.4.2
	   \-- com_eliotlash_mclib_mclib 20
	- held-item-info 1.5.0
	- indium 1.0.30+mc1.20.4
	- inventoryhud 3.4.18
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- jei 15.3.0.1
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- lazydfu 0.1.3
	- lithium 0.11.2
	- lithostitched 1.1.5
	- memoryleakfix 1.1.5
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- modmenu 7.2.2
	- moreculling 1.20.4-0.22.1
	   |-- conditional-mixin 0.3.2
	   \-- mixinsquared 0.1.1
	- morecullingextra 1.1-1.20.1
	- notenoughanimations 1.7.1
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- plasmovoice 2.0.8
	   |-- aopalliance_aopalliance 1.0
	   |-- com_google_inject_guice 5.0.1
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- javax_inject_javax_inject 1
	- player-animator 1.0.2-rc1+1.20
	- promenade 4.1.1
	   \-- biolith 1.0.0-alpha.8
	        \-- terraform-surfaces-api-v1 7.0.1
	- railoptimization 1.0
	- realcamera 0.5.5-beta
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- sodium 0.5.8+mc1.20.1
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sound_physics_remastered 1.20.1-1.3.1
	- starlight 1.1.2+fabric.dbc156f
	- travelersbackpack 1.20.1-9.1.9
	- trinkets 3.7.1
	- visuality 0.7.1+1.20
	- waveycapes 1.3.2
	- wildlife 1.19.2-2.2
	- yet_another_config_lib_v3 3.2.1+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- zoomify 2.11.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
[08:44:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/mixak/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[08:44:13] [main/INFO]: Compatibility level set to JAVA_17
[08:44:13] [main/INFO]: Initializing com.ishland.c2me.base.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.client.uncapvd.mixin
[08:44:14] [main/INFO]: Disabling config clientSideConfig.modifyMaxVDConfig.enabled: Incompatible with bobby@5.0.1 (*) (defined in c2me)
[08:44:14] [main/INFO]: Disabling com.ishland.c2me.client.uncapvd.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.fixes.chunkio.threading_issues.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.fixes.general.threading_issues.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.threading_issues.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.vanilla_bugs.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.notickvd.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.opts.allocs.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.opts.chunk_access.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.opts.chunkio.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.opts.math.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.opts.scheduling.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.general.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.vanilla.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunk_serializer.mixin
[08:44:14] [main/INFO]: Disabling com.ishland.c2me.rewrites.chunk_serializer.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunkio.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.server.utils.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.threading.chunkio.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.threading.lighting.mixin
[08:44:14] [main/INFO]: Initializing com.ishland.c2me.threading.worldgen.mixin
[08:44:14] [main/WARN]: Reference map 'ctov-fabric-refmap.json' for ctov.mixins.json could not be read. If this is a development environment you can ignore this message
[08:44:14] [main/WARN]: Reference map 'ctov-common-refmap.json' for ctov-common.mixins.json could not be read. If this is a development environment you can ignore this message
[08:44:14] [main/WARN]: Reference map 'entity_model_features_fabric_1.20.1-fabric-refmap.json' for entity_model_features.mixins.json could not be read. If this is a development environment you can ignore this message
[08:44:14] [main/WARN]: Reference map 'de-guntram-mcmod-fabrictools-refmap.json' for mixins.de-guntram-mcmod-fabrictools.json could not be read. If this is a development environment you can ignore this message
[08:44:14] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 2 override(s) found
[08:44:14] [main/WARN]: Reference map 'memoryleakfix-fabric-1.17+-fabric-refmap.json' for memoryleakfix-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[08:44:14] [main/WARN]: [Satin] Iris is present, custom block renders will not work
[08:44:14] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 4 override(s) found
[08:44:14] [main/INFO]: Loaded configuration file for Sodium Extra: 34 options available, 0 override(s) found
[08:44:14] [main/WARN]: Reference map 'wildlife-refmap.json' for wildlife.mixins.json could not be read. If this is a development environment you can ignore this message
[08:44:15] [main/WARN]: Error loading class: net/minecraft/client/font/FontManager$1 (java.lang.ClassNotFoundException: net/minecraft/client/font/FontManager$1)
[08:44:15] [main/WARN]: @Mixin target net/minecraft/client/font/FontManager$1 was not found dashloader.mixins.json:option.cache.font.FontManagerOverride from mod dashloader
[08:44:15] [main/WARN]: Error loading class: dev/tr7zw/skinlayers/render/CustomizableModelPart (java.lang.ClassNotFoundException: dev/tr7zw/skinlayers/render/CustomizableModelPart)
[08:44:15] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[08:44:15] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me]) disables it and children
[08:44:15] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[08:44:15] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[08:44:15] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[08:44:15] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[08:44:15] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[08:44:15] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[08:44:15] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[08:44:15] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[08:44:15] [main/WARN]: Force-disabling mixin 'features.shader.uniform.ShaderProgramMixin' as rule 'mixin.features.shader.uniform' (added by mods [dashloader]) disables it and children
[08:44:16] [main/INFO]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[08:44:16] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[08:44:16] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[08:44:16] [main/INFO]: I used the json to destroy the json
[08:44:16] [main/INFO]: Searching for graphics cards...
[08:44:16] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[08:44:17] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=Radeon RX 5500 XT, version=DriverVersion=31.0.23013.3005]
[08:44:18] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[08:44:19] [main/WARN]: Method overwrite conflict for getPausedTickDelta in entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features, previously written by carpet.mixins.Minecraft_pausedShakeMixin. Skipping method.
[08:44:20] [main/WARN]: Method overwrite conflict for method_5800 in carpet-fixes.mixins.json:itemFixes.ItemEntity_lightningKillsDropsMixin from mod carpet-fixes, previously written by carpet.mixins.ItemEntityMixin. Skipping method.
[08:44:20] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2442 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2442 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[Fabric%201.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[Fabric%201.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method modifyUpdate(I)I in carpet-fixes.mixins.json:blockUpdates.duplicateUpdates.PoweredRailBlock_updateMixin from mod carpet-fixes failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap carpet-fixes-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[Fabric%201.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 2 more

**Comment by Carloix** [comment]
having that error too, had to temporarily unninstall it in order to play :/

**Comment by LambdAurora** [comment]
This specific crash does not seem to be linked to LambDynamicLights specifically.
Feel free to re-open if you have further evidence that it is caused by it.
