### ISSUE TITLE
Crashes on save

### ISSUE THREAD

**Issue by skylorbeck** [LambdAurora/LambDynamicLights#37]
Whenever saving happens, the entire game crashes. 

[2020-11-12-5.log.gz](https://github.com/LambdAurora/LambDynamicLights/files/5534573/2020-11-12-5.log.gz)

Appears to be a conflict with Immersive Portals. Didn't happen until today. Relevant part 

```[19:15:57] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at net.minecraft.class_761.method_3295(class_761.java:2497) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_761.lambdynlights_scheduleChunkRebuild(class_761.java) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at me.lambdaurora.lambdynlights.LambDynLights.scheduleChunkRebuild(LambDynLights.java:414) ~[lambdynamiclights-fabric-1.3.2+1.16.4.jar:?]
	at net.minecraft.class_1297.lambdynlights_scheduleTrackedChunksRebuild(class_1297.java:5334) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at me.lambdaurora.lambdynlights.LambDynLights.clearLightSources(LambDynLights.java:326) ~[lambdynamiclights-fabric-1.3.2+1.16.4.jar:?]
	at net.minecraft.class_310.handler$znb001$onSetWorld(class_310.java:7319) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:1922) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_634.method_11117(class_634.java:1049) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_2724.method_11782(class_2724.java:40) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_2724.method_11054(class_2724.java:14) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_2600$$Lambda$5493/1717568013.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:990) [intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227) [fabric-loader-0.10.0+build.208.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.10.0+build.208.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.10.0+build.208.jar:?] 
```

**Comment by LambdAurora** [comment]
Fixed in 1.3.3.
