### ISSUE TITLE
weird message in log file, sharing in case it helps

### ISSUE THREAD

**Issue by Nicolas-GE** [LambdAurora/LambDynamicLights#74]
`[04:08:59] [Render thread/WARN]: Unable to find LambDynLights render hook due to exception:
java.lang.ClassNotFoundException: me.lambdaurora.lambdynlights.LambDynLights
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at grondag.canvas.compat.LambDynLightsHolder.<clinit>(LambDynLightsHolder.java:39) ~[canvas-mc117-1.17-1.0.1802.jar:?]
	at grondag.canvas.compat.Compat.lambda$init$0(Compat.java:32) ~[canvas-mc117-1.17-1.0.1802.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents.lambda$static$1(WorldRenderEvents.java:64) ~[43e10557-b158-4c4e-8008-7f595b0ebb37.jar:?]
	at grondag.canvas.render.world.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:768) [canvas-mc117-1.17-1.0.1802.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[04:09:00] [Render thread/INFO]: Found MaliLib - compatibility hook enabled`

Using `lambdynamiclights-2.0.1+1.17`, `fabric-loader-0.11.6-1.17.1`, `fabric-api-0.37.0+1.17`, `lithium-fabric-mc1.17.1-0.7.3`, `modmenu-2.0.2` and `malilib-fabric-1.17.1-0.10.0-dev.24`

i'm not sure if this is an issue but i'm reporting it anyways, because this might be a problem

**Comment by LambdAurora** [comment]
This must be reported to Canvas instead.

**Comment by Nicolas-GE** [comment]
didn't realize this was a Canvas log/issue, should i close this then?
